stages:
 - terraform


terraform-job:
  stage: terraform
  image: 
    name: hashicorp/terraform:1.7.5
    entrypoint:
      - '/usr/bin/env'
      - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
  script:
    - echo "This is sample Init Command"
    - terraform version 